### ISSUE TITLE
Model size?

### ISSUE THREAD

**Issue by GothkittyGirl** [AdvancedPlugins/Models#2]
### Describe the bug

Model candle size on the chandelier are so tiny vers the ones on the test server

### How to reproduce

idk just like that on getting them
Yours:
![hostserver](https://github.com/user-attachments/assets/137916fd-1efa-4c00-9e55-b9bb5b483476)
Mine:
![server1](https://github.com/user-attachments/assets/2cae2311-06f8-489a-af39-6219f93ff74e)

**Comment by GC-spigot** [comment]
Fixed next update :) You will have to delete the `models` folder inside `plugins/AdvancedModels/` and restart the server with new version.
