### ISSUE TITLE
Removed from discord and issues not fixed

### ISSUE THREAD

**Issue by jonaas13** [AdvancedPlugins/Models#7]
### Describe the bug

I was removed from the discord. 
My questions weren't answered and I had to find out fixes myself. 
When I opened the .jar file to fix it the developer got mad. 
I am unable to ask for support for my other advanced plugins. 
You have lost me as a customer. I won't hide this story from the public. 

### How to reproduce

Ask a question. Report a bug. 
Wait around until you get kicked out.

**Comment by GC-spigot** [comment]
You were refunded for your payment and kicked off the discord for spreading misinformation.

**Comment by jonaas13** [comment]
> You were refunded for your payment and kicked off the discord for spreading misinformation.

Sure if that's how you want to play it.
